name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: BUILD
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v2
      - name: NODE
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn build
        env:
          CI: false
      - name: DEPLOY
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "vetnow-management-frontend"
          heroku_email: "vetnowcontato@gmail.com"
      - name: RELEASE
        needs: DEPLOY
        run: |
          git config --global user.email "ci@vetnow.com.vc"
          git config --global user.name "Vetnow CI"
          yarn version --patch
          git push --tags && git push

