name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v2
      - name: NODE
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: BUILD
        run: |
          yarn install
          yarn build
        env:
          CI: false
      - name: DEPLOY
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "vetnow-management-frontend"
          heroku_email: "vetnowcontato@gmail.com"
      - name: RELEASE
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
          yarn version --patch
          git push --tags && git push

