name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn build
        env:
          CI: false
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Implementar teste"
